### ISSUE TITLE
Created AUR package for Arch users

### ISSUE THREAD

**Issue by vasket** [39aldo39/Evolution-DecSync#10]
Hello 39aldo39,

Thanks for this nice pice of software.

I've provided a PKGBUILD for the aur. Feel free to mention it somewhere.

**Comment by 39aldo39** [comment]
Thanks!

You should change the license to LGPL2 though. You also made a small type in Evolution.

**Comment by vasket** [comment]
Done

**Comment by 39aldo39** [comment]
Sorry, I made a typo myself... I meant LGPL not LGPL2. Sorry for the inconvenience.

**Comment by vasket** [comment]
Happens sometimes, updated the build.
