### ISSUE TITLE
Release 1.0.1 segfaults on ubuntu 19.04 for contacts

### ISSUE THREAD

**Issue by pietervdvn** [39aldo39/Evolution-DecSync#11]
Since I upgraded to ubuntu 19.04, I had to reinstall the .deb package. It worked once, but the next reboot, evolution told me it could not connect to decsync.

When executing: `/usr/lib/evolution-data-server/addressbook-backends/libebookbackenddecsync.so`, I get 'segmentation fault (core dumped)'.

Any help or idea? I can provide logs if you can instruct me on how to obtain them.

**Comment by 39aldo39** [comment]
I can reproduce this in Debian (testing). I am not sure what the problem is, but repackaging seems to fix it. Can you verify that version 1.0.2 works?

As a side note: you shouldn't execute `libebookbackenddecsync.so` directly, it is used by `/usr/lib/evolution/evolution-addressbook-factory`.

**Comment by pietervdvn** [comment]
Hey,

Works like a charm now!

Yes, I know I'm not supposed to manually execute those files, I was just messing around to figure out what broke before asking you.

**Comment by pietervdvn** [comment]
PS: thanks for the awesome tool
