### ISSUE TITLE
Broken on Gnome 3.34

### ISSUE THREAD

**Issue by iexos** [39aldo39/Evolution-DecSync#15]
My decsync calendar and contacts are not working anymore

I am using Arch Linux, Evolution 3.34.0 with the evolution-decsync AUR package. The AUR package does not build anymore either.

**Comment by 39aldo39** [comment]
It looks like there are indeed some changes in the Evolution Data Server. I will update the backend code to incorporate the changes. Thanks for the notice!

**Comment by 39aldo39** [comment]
I have updated the code to incorporate the changes. Can you confirm that it works?

**Comment by iexos** [comment]
Yep, its working again. :tada: 
Thank you very much!
