### ISSUE TITLE
Error when trying to sync calendar

### ISSUE THREAD

**Issue by Triton171** [39aldo39/Evolution-DecSync#16]
I have set up DecSync for Evolution and Contact Sync works just fine. However when I try to show my Decsync calendar, Evolution displays the error:

Failed to open calendar “DecSync : [Calendar Name]”
Unable to connect to “[Calendar Name]”: Backend factory for source “d517818f7ba936e58e58a58c787635b16f2b7e01” and extension “Calendar” cannot be found.

**Comment by 39aldo39** [comment]
Could you provide the following info?
- What is your distro?
- How did you install Evolution DecSync and what version?
- What is your Evolution version (execute `evolution --version`)?

**Comment by Triton171** [comment]
- I'm using Ubuntu 18.04.03
- I installed Evolution DecSync using the evolution-decsync-v1.0.3.deb file on the releases page
- My evolution version is: evolution 3.28.5-0ubuntu0.18.04.1

**Comment by 39aldo39** [comment]
The problem has to do with different versions of Evolution, they depend on different versions of some libraries.

I have added more deb-packages on the release page, you should install `evolution-decsync-v1.0.3-evolution-3.28.deb`. Does that one work for you?

**Comment by Triton171** [comment]
The new release works perfectly, thanks a lot.

**Comment by peterflock** [comment]
I have same issue:
* `Ubuntu 20.04.2 LTS`
```
$ evolution --version                                      
evolution 3.36.4-0ubuntu1 

$ sudo dpkg -i libdecsync-v1.8.3.deb
$ sudo dpkg -i evolution-decsync-v1.3.0-evolution-3.36.deb
```

```
Unable to open address book “Contacts”

This address book cannot be opened.  This either means that an incorrect URI was entered, or the server is unreachable.

Detailed error message: Unable to connect to “XXXXXXXXX”: Backend factory for source “XXXXXXXXX” and extension “Address Book” cannot be found.
```

**Comment by peterflock** [comment]
The problem was that I did NOT restarted PC. After the restart it works now.
