### ISSUE TITLE
Not working well with gnome-calendar

### ISSUE THREAD

**Issue by moritztk** [39aldo39/Evolution-DecSync#18]
While it works well on evolution itself, for some reason it has issues with gnome-calendar, like events that cannot be deleted.

**Comment by 39aldo39** [comment]
Strange, as it makes no difference for the backend. I don't use Gnome Calendar often myself, but I am able to delete events. Can't you delete some events, or all?

Could you provide the following information?
- What distro are you using?
- How did you install Evolution DecSync and what version?
- What are the results of `evolution --version` and `gnome-calendar --version`?

**Comment by moritztk** [comment]
> What distro are you using?
Fedora 30

> How did you install Evolution DecSync and what version?
I followed [this guide](https://github.com/39aldo39/Evolution-DecSync/tree/evolution-3.30#fedora)

> What are the results of evolution --version and gnome-calendar --version?
gnome-calendar: Version 3.32.2
evolution 3.32.4 (3.32.4-1.fc30)

IIRC this was the way to reproduce it:
- [Android] create repeating event (e.g. daily)
- [Android] change one instance of the repeating event
- [gnome-calendar] try deleting that event

Later today or tomorrow I will be able to confirm if those were the exact steps

**Comment by 39aldo39** [comment]
Indeed, recurring events with exceptions behave weird. Actually, Gnome Calendar cannot handle them well at all. If you do your Android steps in Gnome Calendar, you get the same behavior. You also don't have to change an instance first.

See also [their](https://gitlab.gnome.org/GNOME/gnome-calendar/issues/399) bug report.
