### ISSUE TITLE
Not working in fedora

### ISSUE THREAD

**Issue by adamsson6** [39aldo39/Evolution-DecSync#2]
Hi, i'm trying to compile it in fedora and it doesn't find dependencies.
I also tried to install the dependencies manually and copy the library ".so" files from compiled version of ubuntu, and put them manually in all library folders, but I have this error when I'm trying to launch evolution : 
```

(evolution:9410): e-data-server-WARNING **: 19:51:18.928: module_load: libevolution-util.so.0: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib64/evolution/modules/module-book-config-decsync.so

(evolution:9410): e-data-server-WARNING **: 19:51:18.933: module_load: libevolution-util.so.0: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib64/evolution/modules/module-cal-config-decsync.so

```
EDIT : one problem solved, the name of the library was wrong, i copied it with the right name : libevolution.util.so.0 but no i'm having another "pathfinding" error : 

`(evolution:9816): evolution-util-WARNING **: 19:54:58.175: source_config_init_for_adding_source: ECalConfigDecsyncClass specifies an invalid parent_uid 'decsync'
`

EDIT 2 : Second problem solved ! I just made a mistake on the path of decsync.source : I put the file in "/usr/share/evolution-decsync/" instead of "/usr/share/evolution-decsync/sources/".

Now, evolution is showing decsync in calendar menu ! Now I will try to sync calendar...

EDIT 3 : New error in the interface of evolution when syncing. The plugin see the calendar, but when I want it to sync i got the error (in french sorry) :
`
 Impossible de se connecter à « agenda » : Impossible de trouver un créateur de moteur pour la source « 041d40b47c9166bf5bf59949c3763b6c2a50db84 » et l’extension « Calendar ».`

EDIT 4 : Contacts sync is working, but calendar sync not.

**Comment by adamsson6** [comment]
Precision : I'm saying that the library libevolution-util.so.0 is in the filder /usr/lib64/evolution

**Comment by 39aldo39** [comment]
I think you should focus on making compiling work, instead of hacking the library files together. What is the output when you try to compile? Fedora uses a different naming scheme for development packages. It uses the `-devel` suffix instead of `-dev`. The names also might be slightly different.

**Comment by adamsson6** [comment]
I successully compiled it in fedora thanks. But i had to manually install dependencies packages searching name after name.
Works great now, thank you very much.

**Comment by 39aldo39** [comment]
I have updated the README now to include Fedora dependencies as well.
