### ISSUE TITLE
What is the right version for Evolution-DecSync on Debian Stretch with Evolution 3.22.6?

### ISSUE THREAD

**Issue by snm247** [39aldo39/Evolution-DecSync#24]
Currently the releases page only shows versions for Evolution 3.28, 3.30 and 3.34. Is there any Evolution-DecSync version that can be used with [Evolution 3.22.6 on Debian Stretch](https://packages.debian.org/stretch/evolution)?

**Comment by 39aldo39** [comment]
You could try version 3.28, it might or might not work.

If it doesn't work you could try compiling from source. Make sure to checkout the `evolution-3.30` branch as it does not contain changes for newer Evolution versions. Also, I am willing to support Debian stable, but I won't support the old stable, as that is too much to support for me. But I can help if you have issues compiling.

**Comment by snm247** [comment]
Thank you for your answer. Maybe I'll just update Debian first before trying DecSync.
