### ISSUE TITLE
extension disappears after restart

### ISSUE THREAD

**Issue by visir** [39aldo39/Evolution-DecSync#28]
Hi there!

I install the .deb package from https://github.com/39aldo39/Evolution-DecSync/releases on an ubuntu 18.04.4 LTS, it's visible as extension in the software app, and according to the guide, I restart the computer - and it's gone. No DecSync options in Evolution. Tried more than once to be shure.
What could be the problem?
Thanks a lot in advance for help!

BR, Wolfgang

**Comment by 39aldo39** [comment]
The problem is that you installed the wrong version. Ubuntu 18.04 uses Evolution 3.30, so that version has to be used. I updated the release page to make it clearer (it wasn't). It does mean that you have to install an old version, but that works fine as well.

**Comment by visir** [comment]
thank you, now it worked just fine!
