### ISSUE TITLE
DecSync calendar accounts are moved to contacts and not synchronized

### ISSUE THREAD

**Issue by visir** [39aldo39/Evolution-DecSync#30]
Hello there,

I'm happy that there is finally a reasonable solution for synchronizing contacts and calendars. If it would work properly...
contacts seem to work fine so far (although one recent change is not yet synchronized), but whenever I create a calendar account in evolution, after some time (even without restart of Evolution) the calendar account is moved to the address books. 
![grafik](https://user-images.githubusercontent.com/68778393/89119884-e258ed00-d4b1-11ea-84ce-ddb688859287.png)

At the beginning, decsync at the smartphone showed a lot of calendar entries, though I didn't see them in the calendar, but now they are reduced to three in the DecSync app, one of them created on Android and still visible there (but not in Evolution), and I won't search for the other two...
Thanks in advance for help!

**Comment by 39aldo39** [comment]
This is indeed a weird bug. It is mostly solved in version 1.1.0, but that one isn't available for Ubuntu 18.04. I have now updated that package as well to incorporate the fix. If you install version 1.0.5 it should be fixed (after restarting and re-adding the collection).

As a side note, in my experience the calendar collection is added as an address book as well, but continues to work as a calendar. I see that it is moved in the 'Accounts' tab, but it is also still available as a calendar.

**Comment by visir** [comment]
Sorry for replying so late, but I was really busy lately, and the notification was repeatedly(!) moved to the spam folder. I just remembered that there was something...

Version 1.0.5 is for Evolution 3.30, but I have 3.28 - ?

**Comment by 39aldo39** [comment]
Sorry, I updated the wrong version. The right version should be available now.

**Comment by visir** [comment]
thank you for that, at the moment I'm busy with family things, I'll check that later.

**Comment by visir** [comment]
finally... I get back to this. And it seems to work. Thanks a lot!

**Comment by visir** [comment]
...nooo, it did it again...

**Comment by visir** [comment]
well. after a restart of the computer (and deleting and setting up everything new) it seems to work properly. Finally, I get a message on the phone "adding events of <calendar>", although its there for about two hours... but this is a different thing.
