### ISSUE TITLE
upgraded to ubuntu 20.04 LTS/ Evolution 3.36 - decsync is gone, installation fails, "not supported"

### ISSUE THREAD

**Issue by visir** [39aldo39/Evolution-DecSync#33]
Hi, it's me again! ;)

The title says it basically: upgraded my Ubuntu and with it Evolution. There are still the Decsync accounts, but e.g. the calendar is unchecked, and if I try to check it, it says it couldn't be opened/ connection has failed because backend for source »48b80021757fc685a9b65d677bb4fe50bd241833« and extension »Calendar« could not be found (manually translated). Basically the same for the address book.

So I thought the extension is gone (and it is in fact not listed in the extensions), so I tried to install it again like before, but it says - see title. For the libdecsync as well as for the extension itself.

What can I do?
Thanks in advance for help!

Best regards,
Wolfgang

**Comment by 39aldo39** [comment]
There are two things I can think of: did you install the 3.36 version, and did you restart your computer? That might be needed. If that was fine, could you start `evolution` from the terminal and see what it logs?

And it's good that you post these issues! I try to make using DecSync simple, so it is always good to know what issues users have.

**Comment by visir** [comment]
The log from the terminal:
`(evolution:7703): e-data-server-WARNING **: 20:54:28.017: module_load: libedataserver-1.2.so.23: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Failed to load module: /usr/lib/evolution/modules/module-cal-config-decsync.so

(evolution:7703): e-data-server-WARNING **: 20:54:28.038: module_load: libedataserver-1.2.so.23: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
Failed to load module: /usr/lib/evolution/modules/module-book-config-decsync.so

(evolution-alarm-notify:7714): GLib-GIO-WARNING **: 20:54:28.187: Your application did not unregister from D-Bus before destruction. Consider using g_application_run().
`
And when I open the properties of one of the DecSync objects in evolution, the log proceeds:
`(evolution:7807): evolution-util-CRITICAL **: 21:00:28.746: source_config_init_for_editing_source: assertion 'backend != NULL' failed

(evolution:7807): evolution-util-CRITICAL **: 21:00:28.746: source_config_get_active_candidate: assertion 'index >= 0' failed

(evolution:7807): evolution-util-CRITICAL **: 21:00:28.746: e_source_config_check_complete: assertion 'candidate != NULL' failed
`

That should be some information about the problem...

**Comment by 39aldo39** [comment]
Are you sure you installed the package `evolution-decsync-v1.2.0-evolution-3.36.deb`? It looks like you still have the old version installed.

**Comment by visir** [comment]
Then the old version is still there from before the upgrade, but not working. As mentioned before, the installation of the new package failed.

**Comment by 39aldo39** [comment]
Oh, I see. I thought it failed in the sense that it didn't work in Evolution, but the installation itself failed. I can now reproduce it in a VM. The installation using the software center fails, but installing it by executing `sudo dpkg -i evolution-decsync-v1.2.0-evolution-3.36.deb` works fine. I will keep the issue open until I find out why the normal installation fails.

**Comment by visir** [comment]
sudo worked (first libdecsync, then evolution-decsync), everything synchronized again - thanks for that hint!

**Comment by visir** [comment]
just funny that decsync doesn't show up in the evolution extensions - should it bei visible somewhere?

**Comment by 39aldo39** [comment]
> just funny that decsync doesn't show up in the evolution extensions - should it bei visible somewhere?

No, it doesn't. I'm not sure how the plugin screen works, but I don't think it should show up. For example, `evolution-ews` also doesn't show up in that screen.

> I will keep the issue open until I find out why the normal installation fails.

It turns out that this is a strange problem in Ubuntu 20.04. It doesn't work when installing from `/tmp/mozilla_userX` (this is where it is stored when opening it directly), but does work from other places like `/home/user`. See [this answer](https://askubuntu.com/a/1245049).
