### ISSUE TITLE
Build error on Fedora 33  - "evolution-shell-3.0" not found

### ISSUE THREAD

**Issue by marvkal** [39aldo39/Evolution-DecSync#35]
OS: Fedora 33
Evolution 3.38.1-1.fc33

Following the build instructions for Fedora, having checked out the `evolution-3.38` branch, I get a missing dependency error during the `meson build` stage.:

`meson.build:11:0: ERROR: Dependency "evolution-shell-3.0" not found, tried pkgconfig and cmake`

I did install all dependencies including `evolution-devel`, and have `evolution-shell-3.0.pc` files in `/lib64/pkgconfig` as well as `/usr/lib64/pkgconfig`.

I'm probably missing something basic, seeing as I have no experience with C and little experience compiling software.

Here's the [meson-log.txt](https://github.com/39aldo39/Evolution-DecSync/files/5505584/meson-log.txt) for more details.

Thanks in advance!

**Comment by 39aldo39** [comment]
I'm not sure what went wrong. I tried it in Fedora 33 as well, and everything went fine. Could you give the output of `pkg-config --modversion evolution-shell-3.0`?

**Comment by marvkal** [comment]
It builds now! Not sure what the problem ended up being, I haven't changed anything in the meantime apart from upgrading packages.
