### ISSUE TITLE
Support Tasks

### ISSUE THREAD

**Issue by Torenga** [39aldo39/Evolution-DecSync#37]
Thank you for including OpenTasks, this has also spurred Tasks.org to put DecSync-support on the roadmap! I'm looking forward to the future of DecSync on mobile.

But there's seemingly no Evolution task support, leaving the task support as an android-only sync or in my case (one mobile device, one desktop) as a single device backup with no sync at all.

Is it possible to update the Evolution plug-in to support tasks? I'm happily running Calendar and Contact sync at the moment but is forced to step outside the box and use todo.txt and affiliate apps to achieve task sync support over Syncthing.

Thank you for considering.

**Comment by 39aldo39** [comment]
Glad you like it! And I have actually added support for tasks in Evolution! But I still have to package it as `.deb`'s, which I should do soon.

**Comment by 39aldo39** [comment]
The `.deb`'s are published now!
