### ISSUE TITLE
Installation on Kubuntu 20.10 fails

### ISSUE THREAD

**Issue by msbavaria** [39aldo39/Evolution-DecSync#38]
`libdecsync-v1.8.3.deb` installs properly, but `evolution-decsync-v1.3.0-evolution-3.38.deb` fails afterwards because it expects `libjson-c4` and only `libjson-c5` is available on the system.

**Comment by jonathanherrmannengel** [comment]
same with debian 11 bullseye

but works fine with libjson-c5 for me after changing dependency at evolution-decsync-v1.3.0-evolution-3.38.deb

**Comment by JacobRoth** [comment]
Looks like this is still an issue with V2.0.0. The deb package still only accepts libjson-c4

Is compiling from source my only option here?
