### ISSUE TITLE
Not showing on mx17 (debian)

### ISSUE THREAD

**Issue by cerisara** [39aldo39/Evolution-DecSync#4]
Installed the released .dep with dkpg without errors, but the plugin is not visible shows up in evolution

**Comment by 39aldo39** [comment]
You may need to restart your computer to make Evolution reload the libraries (it also has some background processes). If that doesn't work, can you check whether `~/.config/evolution/sources/decsync.source` exists?

**Comment by cerisara** [comment]
Thank you, sorry I cannot test any more, so it's better to close this issue.
Sorry I cannot follow-up !
