### ISSUE TITLE
update decsync?

### ISSUE THREAD

**Issue by visir** [39aldo39/Evolution-DecSync#48]
Hello there,

maybe it's a dumb question, but Evolution seems to have a version problem with decsync:
Uncaught Kotlin exception: org.decsync.library.UnsupportedVersionException
maybe after a recent update.
So I thought it might help to update decsync, but I can't find any description how to do it properly. Just downloading  the recent installation package and double clicking it starts the software app, offering me to deinstall decsync... and I'm afraid I might lose data if I do that.

So how to update it properly?
And could that be added in the readme?

Best regards!

**Comment by visir** [comment]
thank you for that- this too offers me to deinstall first, when I double click it and it opens in ubuntu software - ?
![grafik](https://user-images.githubusercontent.com/68778393/153942540-06a4e9d7-40f2-4083-870d-630e169f4c34.png)

**Comment by 39aldo39** [comment]
I don't understand what Ubuntu Software is trying to do (it can be counterintuitive sometimes), but if you try installing it in the terminal with `sudo dpkg -i libdecsync-v2.2.1.deb` it should give more information about what it is doing.

**Comment by visir** [comment]
Well, it's already there (in whatever version), so the logical thing for Ubuntu Software is to deinstall - ?

Installing in the terminal worked and solved the problem, thanks!

Could the procedure of updating be added in the readme? Might help others like me. ;)
