### ISSUE TITLE
contact won't sow up in deban

### ISSUE THREAD

**Issue by privat-mayhem** [39aldo39/Evolution-DecSync#5]
hello there, 

i managed to compile the extension myself. Calendarsync is working fine, but contacts won't show up. I am able to select the created adressbook, but the contacts dose not show up.

The adressbook and the calendars were created on android.

Last but not least thank you for this pice of code.

**Comment by privat-mayhem** [comment]
Don't know if it helps but the calendar entries showing up as contact books with an error:
![screenshot from 2018-12-09 16-33-40](https://user-images.githubusercontent.com/45732790/49699385-c4e65980-fbd0-11e8-8b7b-2bcdc52bb81a.png)

first entrie is the adressbook.

on my debian are entries form my android and an empty folder for debian resoruces

if you need something help don't hesitate to ask.

**Comment by privat-mayhem** [comment]
Strange things happens... contacts are there now, after over a day of use...

**Comment by 39aldo39** [comment]
Very weird, the calendars and contacts are separate from each other and should never interact...

But does it work fine now? Maybe you have restarted something which made it work.

**Comment by privat-mayhem** [comment]
syncing works now as expected. calendars still showing up in the contact section.

I've deleted my `.cache` directory. maybe it caused evolution somehow...
