### ISSUE TITLE
Build fails on Manjaro (both AUR and manual)

### ISSUE THREAD

**Issue by alessandro-cojp** [39aldo39/Evolution-DecSync#52]
**Hi everyone, I'm trying to install this plugin however it the build fails saying a failure occurred in build()
It seems to be related to deprecated GTimeVal functions. Here the Meson build system terminal output:**

The Meson build system
Version: 0.62.0
Source dir: /home/alessandro/.cache/yay/evolution-decsync/src/Evolution-DecSync-2.0.1-evolution-3.44
Build dir: /home/alessandro/.cache/yay/evolution-decsync/src/Evolution-DecSync-2.0.1-evolution-3.44/build
Build type: native build
Project name: evolution-decsync
Project version: 2.0.1-evolution-3.40
C compiler for the host machine: cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libedata-book-1.2 found: YES 3.42.4
Run-time dependency libedata-cal-2.0 found: YES 3.42.4
Run-time dependency evolution-shell-3.0 found: YES 3.42.4
Run-time dependency json-c found: YES 0.15
Run-time dependency decsync found: YES 2.2.1
Configuring evolution-decsync-config.h using configuration
Build targets in project: 4
NOTICE: Future-deprecated features used:
 * 0.56.0: {'dependency.get_pkgconfig_variable'}

Found ninja-1.10.2 at /usr/bin/ninja
ninja: Entering directory `build'
[1/19] Compiling C object src/backends...o.p/e-book-backend-decsync-factory.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from /usr/include/evolution-data-server/libebook-contacts/libebook-contacts.h:23,
                 from /usr/include/evolution-data-server/libedata-book/libedata-book.h:23,
                 from ../src/backends/addressbook/e-book-backend-decsync.h:31,
                 from ../src/backends/addressbook/e-book-backend-decsync-factory.c:26:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/evolution-data-server/libedataserver/e-cancellable-locks.h:31,
                 from /usr/include/evolution-data-server/libedataserver/libedataserver.h:23,
                 from /usr/include/evolution-data-server/libebook-contacts/libebook-contacts.h:23,
                 from /usr/include/evolution-data-server/libedata-book/libedata-book.h:23,
                 from ../src/backends/addressbook/e-book-backend-decsync.h:31,
                 from ../src/backends/addressbook/e-book-backend-decsync-factory.c:26:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[2/19] Compiling C object src/backends....p/.._.._e-source_e-source-decsync.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/evolution-data-server/libedataserver/e-cancellable-locks.h:31,
                 from /usr/include/evolution-data-server/libedataserver/libedataserver.h:23,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[3/19] Compiling C object src/backends....so.p/e-cal-backend-decsync-events.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from /usr/include/evolution-data-server/libecal/libecal.h:26,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.c:25:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/libical-glib/libical-glib.h:22,
                 from /usr/include/evolution-data-server/libecal/libecal.h:25,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.c:25:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[4/19] Compiling C object src/backends...so.p/e-cal-backend-decsync-journal.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from /usr/include/evolution-data-server/libecal/libecal.h:26,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-journal.h:24,
                 from ../src/backends/calendar/e-cal-backend-decsync-journal.c:21:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/libical-glib/libical-glib.h:22,
                 from /usr/include/evolution-data-server/libecal/libecal.h:25,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-journal.h:24,
                 from ../src/backends/calendar/e-cal-backend-decsync-journal.c:21:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[5/19] Compiling C object src/backends...ecsync.so.p/e-book-backend-decsync.c.o
FAILED: src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o 
cc -Isrc/backends/addressbook/libebookbackenddecsync.so.p -Isrc/backends/addressbook -I../src/backends/addressbook -Isrc/backends -I../src/backends -Isrc -I../src -I. -I.. -I/usr/include/json-c -I/usr/include/evolution-data-server -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/tss2 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -I/usr/include/nss -I/usr/include/nspr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -pthread '-DBACKENDDIR="/usr/lib/evolution-data-server/addressbook-backends"' -MD -MQ src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o -MF src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o.d -o src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o -c ../src/backends/addressbook/e-book-backend-decsync.c
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/backends/addressbook/e-book-backend-decsync.c:43:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from /usr/include/glib-2.0/glib/gstdio.h:22,
                 from ../src/backends/addressbook/e-book-backend-decsync.c:40:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
../src/backends/addressbook/e-book-backend-decsync.c: In function ‘book_backend_decsync_contains_email_sync’:
../src/backends/addressbook/e-book-backend-decsync.c:1859:9: warning: implicit declaration of function ‘e_book_util_foreach_address’ [-Wimplicit-function-declaration]
 1859 |         e_book_util_foreach_address (email_address, book_backend_decsync_gather_addresses_cb, array);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/backends/addressbook/e-book-backend-decsync.c: In function ‘e_book_backend_decsync_class_init’:
../src/backends/addressbook/e-book-backend-decsync.c:2448:27: error: ‘EBookBackendSyncClass’ {aka ‘struct _EBookBackendSyncClass’} has no member named ‘contains_email_sync’
 2448 |         backend_sync_class->contains_email_sync = book_backend_decsync_contains_email_sync;
      |                           ^~
[6/19] Compiling C object src/backends...c.so.p/e-cal-backend-decsync-todos.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from /usr/include/evolution-data-server/libecal/libecal.h:26,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-todos.h:24,
                 from ../src/backends/calendar/e-cal-backend-decsync-todos.c:24:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/libical-glib/libical-glib.h:22,
                 from /usr/include/evolution-data-server/libecal/libecal.h:25,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-todos.h:24,
                 from ../src/backends/calendar/e-cal-backend-decsync-todos.c:24:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[7/19] Compiling C object src/backends...so.p/e-cal-backend-decsync-factory.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from /usr/include/evolution-data-server/libecal/libecal.h:26,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-factory.c:26:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/libical-glib/libical-glib.h:22,
                 from /usr/include/evolution-data-server/libecal/libecal.h:25,
                 from /usr/include/evolution-data-server/libedata-cal/libedata-cal.h:23,
                 from ../src/backends/calendar/e-cal-backend-decsync.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-events.h:25,
                 from ../src/backends/calendar/e-cal-backend-decsync-factory.c:26:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[8/19] Compiling C object src/backends....p/.._.._e-source_e-source-decsync.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/evolution-data-server/libedataserver/e-cancellable-locks.h:31,
                 from /usr/include/evolution-data-server/libedataserver/libedataserver.h:23,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[9/19] Compiling C object src/modules/....p/.._.._e-source_e-source-decsync.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/evolution-data-server/libedataserver/e-cancellable-locks.h:31,
                 from /usr/include/evolution-data-server/libedataserver/libedataserver.h:23,
                 from ../src/e-source/e-source-decsync.h:22,
                 from ../src/e-source/e-source-decsync.c:21:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
[10/19] Compiling C object src/backend...decsync.so.p/e-cal-backend-decsync.c.o
In file included from /usr/include/evolution-data-server/libedataserver/libedataserver.h:32,
                 from ../src/backends/calendar/e-cal-backend-decsync.c:35:
/usr/include/evolution-data-server/libedataserver/e-flag.h:54:50: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   54 |                                                  GTimeVal *abs_time);
      |                                                  ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from /usr/include/glib-2.0/glib/gstdio.h:22,
                 from ../src/backends/calendar/e-cal-backend-decsync.c:32:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
../src/backends/calendar/e-cal-backend-decsync.c: In function ‘make_revision_string’:
../src/backends/calendar/e-cal-backend-decsync.c:390:9: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
  390 |         GTimeVal timeval;
      |         ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from /usr/include/glib-2.0/glib/gstdio.h:22,
                 from ../src/backends/calendar/e-cal-backend-decsync.c:32:
/usr/include/glib-2.0/glib/gtypes.h:553:8: note: declared here
  553 | struct _GTimeVal
      |        ^~~~~~~~~
../src/backends/calendar/e-cal-backend-decsync.c:394:9: warning: ‘g_get_current_time’ is deprecated: Use 'g_get_real_time' instead [-Wdeprecated-declarations]
  394 |         g_get_current_time (&timeval);
      |         ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/giochannel.h:33,
                 from /usr/include/glib-2.0/glib.h:54,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from /usr/include/glib-2.0/glib/gstdio.h:22,
                 from ../src/backends/calendar/e-cal-backend-decsync.c:32:
/usr/include/glib-2.0/glib/gmain.h:712:8: note: declared here
  712 | void   g_get_current_time                 (GTimeVal       *result);
      |        ^~~~~~~~~~~~~~~~~~
../src/backends/calendar/e-cal-backend-decsync.c:396:9: warning: ‘g_time_val_to_iso8601’ is deprecated: Use 'g_date_time_format' instead [-Wdeprecated-declarations]
  396 |         datestr = g_time_val_to_iso8601 (&timeval);
      |         ^~~~~~~
In file included from /usr/include/glib-2.0/glib.h:89,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from /usr/include/glib-2.0/glib/gstdio.h:22,
                 from ../src/backends/calendar/e-cal-backend-decsync.c:32:
/usr/include/glib-2.0/glib/gtimer.h:73:10: note: declared here
   73 | gchar*   g_time_val_to_iso8601   (GTimeVal    *time_) G_GNUC_MALLOC;
      |          ^~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: evolution-decsync

**Maybe it is an error on my end but I couldn't find any solution**

**Comment by alessandro-cojp** [comment]
Quick follow up, I temporary added -Wno-deprecated-declarations to my makepkg.conf to remove the deprecations errors, now it gives me this error, which seems not related to deprecated functions but to error in code maybe?

The Meson build system
Version: 0.62.0
Source dir: /home/alessandro/.cache/yay/evolution-decsync/src/Evolution-DecSync-2.0.1-evolution-3.44
Build dir: /home/alessandro/.cache/yay/evolution-decsync/src/Evolution-DecSync-2.0.1-evolution-3.44/build
Build type: native build
Project name: evolution-decsync
Project version: 2.0.1-evolution-3.40
C compiler for the host machine: cc (gcc 11.2.0 "cc (GCC) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libedata-book-1.2 found: YES 3.42.4
Run-time dependency libedata-cal-2.0 found: YES 3.42.4
Run-time dependency evolution-shell-3.0 found: YES 3.42.4
Run-time dependency json-c found: YES 0.15
Run-time dependency decsync found: YES 2.2.1
Configuring evolution-decsync-config.h using configuration
Build targets in project: 4
NOTICE: Future-deprecated features used:
 * 0.56.0: {'dependency.get_pkgconfig_variable'}

Found ninja-1.10.2 at /usr/bin/ninja
ninja: Entering directory `build'
[4/19] Compiling C object src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o
FAILED: src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o 
cc -Isrc/backends/addressbook/libebookbackenddecsync.so.p -Isrc/backends/addressbook -I../src/backends/addressbook -Isrc/backends -I../src/backends -Isrc -I../src -I. -I.. -I/usr/include/json-c -I/usr/include/evolution-data-server -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libsecret-1 -I/usr/include/gio-unix-2.0 -I/usr/include/tss2 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -I/usr/include/nss -I/usr/include/nspr -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -Wno-deprecated-declarations -fstack-clash-protection -fcf-protection -fPIC -pthread '-DBACKENDDIR="/usr/lib/evolution-data-server/addressbook-backends"' -MD -MQ src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o -MF src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o.d -o src/backends/addressbook/libebookbackenddecsync.so.p/e-book-backend-decsync.c.o -c ../src/backends/addressbook/e-book-backend-decsync.c
../src/backends/addressbook/e-book-backend-decsync.c: In function ‘book_backend_decsync_contains_email_sync’:
../src/backends/addressbook/e-book-backend-decsync.c:1859:9: warning: implicit declaration of function ‘e_book_util_foreach_address’ [-Wimplicit-function-declaration]
 1859 |         e_book_util_foreach_address (email_address, book_backend_decsync_gather_addresses_cb, array);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/backends/addressbook/e-book-backend-decsync.c: In function ‘e_book_backend_decsync_class_init’:
../src/backends/addressbook/e-book-backend-decsync.c:2448:27: error: ‘EBookBackendSyncClass’ {aka ‘struct _EBookBackendSyncClass’} has no member named ‘contains_email_sync’
 2448 |         backend_sync_class->contains_email_sync = book_backend_decsync_contains_email_sync;
      |                           ^~
[9/19] Compiling C object src/backends/calendar/libecalbackenddecsync.so.p/e-cal-backend-decsync.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: evolution-decsync

**Comment by alessandro-cojp** [comment]
**2nd update: I was cloning from the branch master when trying to compile manually, my fault. 
Compiling from brach 3.38 or 3.40 is successful however the plugin doesn't show up on my Evolution 3.42 install (version from the official Manjaro repo).
The AUR package is confirmed to be broken.**

**Comment by 39aldo39** [comment]
As for the wrong version, I noticed that I forgot to update the requirements. Now it should fail if you are on the wrong branch, making that more clear.

And regarding it not showing up: did you restart you computer? It doesn't immediately show up unfortunately. It is also possible to kill a specific Evolution process, but restarting is simpler.

**Comment by flortsch** [comment]
Building from AUR should also work in Manjaro now - please try it and confirm if this can be closed.

**Comment by alessandro-cojp** [comment]
> Building from AUR should also work in Manjaro now - please try it and confirm if this can be closed.

it requires to trust and import an external signature however it builds and install correctly. Unfortunately it does not appear in the Evolution plug-ins list (yes I rebooted the machine).

update: it doesn't appear in the plugin-ins list but it seems to work regardless, I can select DecSync in calendars/tasks
