### ISSUE TITLE
Doesn't work anymore with Evolution 3.45 on debian testing

### ISSUE THREAD

**Issue by l4nc3l0t** [39aldo39/Evolution-DecSync#57]
With the update of evolution to 3.45 in debian testing I've got this message for my calendars :

Failed to open calendar “DecSync : Work”

Unable to connect to “Work”: Backend factory for source “c7ac3b568e729013eb5b60197f82588f103d0d03” and extension “Calendar” cannot be found.

**Comment by 39aldo39** [comment]
I have added a new version that should work again!

**Comment by l4nc3l0t** [comment]
Sorry but the .deb is not compatible with debian because of zst compression. dpkg for debian doesn't support it, it's an old problem [](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664)

**Comment by 39aldo39** [comment]
Thanks for the heads-up, I have updated it to use xz compression.

**Comment by l4nc3l0t** [comment]
Something is still wrong I've got the same error and couldn't add any calendar. DecSync is not listed in the calendar type...  I tried to delete old decsync-evolution and libdecsync and reinstall, reboot, nothing change

**Comment by l4nc3l0t** [comment]
I tried to build libdecsync and decsync-evolution from source and it's working well by the way

**Comment by 39aldo39** [comment]
I see the problem now and have built a version for Evolution 3.45 specifically as the one for 3.44 is inherently incompatible

**Comment by l4nc3l0t** [comment]
Nice this one is working well. Great job ! Thank you for your reactivity and your work on this useful tool
