### ISSUE TITLE
Cannot parse ICS file

### ISSUE THREAD

**Issue by flortsch** [39aldo39/Evolution-DecSync#59]
I am having an error with Evolution 3.44.4-2 and evolution-decsync 2.1.0-1 on Arch Linux. I can't activate / select my calendar in Evolution. The error is: `Cannot parse ISC file “/home/flortsch/.local/share/evolution/calendar/0a0bb6b9d117fcd8df778fdfbe0ea8e93e8795e3/calendar.ics”`

When I delete and re-create the calendar, it works for a short time. But after syncing it with other devices, it no longer works.

**Comment by holterdipolter** [comment]
Hi,
I was facing the same issue, however this is not decsync related but an issue of a broken evolution-data-server dependency called libical. So downgrading to [libical-3.0.14-3](https://archive.archlinux.org/packages/l/libical/libical-3.0.14-3-x86_64.pkg.tar.zst) did the trick for me.

**Comment by flortsch** [comment]
Indeed, after downgrading to libical-3.0.14-3 it works again. Thank you for the hint!

I will close this issue once the error is fixed in libical, so people can find this more easily.

**Comment by ccat3z** [comment]
Seems fixed in libical 3.0.16-1.

**Comment by flortsch** [comment]
Yep, can also confirm. Will close this issue then :)
